menu:
  Home: /
  Archives: /archives

widgets:
- search
- category
- tag

excerpt_link: Read More

twitter:
  username:
  show_replies: false
  tweet_count: 5

addthis:
  enable: true
  pubid:
  facebook: true
  twitter: true
  google: true
  pinterest: true

fancybox: true

google_analytics:
rss:

# Uncomment the line below to enable facebook commenting 
# comment_provider: facebook
facebook:
  appid: #012345012345 override with your AppId
  comment_count: 5
  comment_width: 840
  comment_colorscheme: light
